### ISSUE TITLE
Density iteration did not converge

### ISSUE THREAD

**Issue by slindorfer** [usnistgov/REFPROP-issues#585]
Hello, I have come across something that I may perceive to be a bug. I have hit a wall with this and felt it would best to reach out here.

### Description

I am using REFPROP for gaseous State Point calculations. The substance I am using is Air, but the issue appears both for the pseudo-pure fluid as well as the mixture. I start with a reference state of known conditions to obtain entropy. As this remains constant in my flow, I use it to obtain the other states  (pressure, temperature, enthalpy) using density. At a certain low-enough value for density, I get the following error in the standalone program, as well as in the Matlab version:

```
[DSFLSH error 248] iteration did not converge:
```

If instead I use pressure to compute the other states (density, temperature, enthalpy), the error does not appear and I can obtain density values well below the one I originally sought.

### Steps to Reproduce

1. Compute entropy using a pressure of 4 MPa and an arbitrary temperature above 1000 K (but below 2000 K). I have opted for 1500 K which yields an entropy of 4.5751 kJ/kg-K
2. Using this entropy, I want to find the other states at certain densities. I am interested in a density of 0.01 kg/m^3 (and values lower than this as well)
3. Error message appears
4. Alternatively, a density of 0.015 kg/m^3 yields a pressure of 0.00058695 MPa but a density of 0.01 kg/m^3 produces the convergence error. Using the same entropy, but driving with a pressure value of 0.0001 MPa (which is significantly lower) I can obtain a density of 0.0042425 kg/m^3

**Expected behavior:** Being able to compute the states using density and entropy as the driver

**Actual behavior:** An iteration error occurs. There appears to be a need to use pressure and entropy as the driver

### Versions

**REFPROP Version:** DLL Version 9.1
**Operating System and Version:** Windows 10
**Access Method:** Standalone, Matlab, Excel

**Comment by ianhbell** [comment]
First, recommend to upgrade to version 10. Some iteration bugs were fixed.

Second, make sure you call SATSPLNdll for the mixture to give the mixture calcs the best chance to converge.

You might need to/want to fall back to a solver to obtain the temperature that yields the given entropy at the given density. That is a one-liner in Python (or MATLAB) with fsolve. It is the only guaranteed solution to this problem.

**Comment by slindorfer** [comment]
Hi, thanks for getting back so quickly!
Are you able to verify that the State Point calculation at that density will work? That would be nice to know in case the upgrade to v10 is all that is needed.

Regarding SATSPLNdll, I am not sure how this is relevant for Air being a pseudo-pure fluid? The substance is not near any phase boundary and is expected to be a gas throughout.

Unfortunately I am already combining both an integral and and fzero (alternative to fsolve) with Matlab to iteratively solve on the density. Based on high-density gas dynamics, this is the only approach I can pursue without creating a separate table to interpolate from.

Many thanks!

**Comment by ianhbell** [comment]
If you treat air as a mixture of fixed composition it is relevant.

Let me try with version 10, one sec.

**Comment by ianhbell** [comment]
With version 10.0, the first failure is for 7.220809018385471e-05 kg/m^3

Code:
```python
import os, numpy as np
os.environ['RPPREFIX'] = os.getenv('HOME')+'/REFPROP10'

import os 
root = os.getenv('RPPREFIX')
import ctREFPROP.ctREFPROP as ct
RP = ct.REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
print(RP.RPVersion())

T0 = 1500 # [K]
p0 = 4e6 # [Pa]

r = RP.REFPROPdll('AIR.PPF','TP','S;D',RP.MASS_BASE_SI,0,0,T0,p0,[0.0])
s,d = r.Output[0:2]
print(r.ierr, r.Output[0])

for f in np.geomspace(1, 1e-10, 100):
    r = RP.REFPROPdll('AIR.PPF','DS','T',RP.MASS_BASE_SI,0,0,d*f,s,[0.0])
    print(f, r.ierr, r.Output[0], r.herr)
    if r.ierr != 0:
        break
```
yielding
```
10.0
0 4575.097744801294
1.0 0 1500.0000000000011 
0.7924828983539173 0 1393.8486335251025 
0.6280291441834253 0 1294.168762368428 
0.4977023564332111 0 1200.509393633355 
0.39442060594376555 0 1112.4685461781253 
0.3125715849688236 0 1029.6895045706915 
0.24770763559917108 0 951.8583185122201 
0.19630406500402708 0 878.7019938393747 
0.1555676143930472 0 809.9867478204723 
0.12328467394420663 0 745.5155936008194 
0.09770099572992251 0 685.1244552370523 
0.0774263682681127 0 628.676119374805 
0.06135907273413173 0 576.0517347666064 
0.04862601580065353 0 527.1403195307413 
0.03853528593710529 0 481.8276558715804 
0.030538555088334154 0 439.98662607611607 
0.02420128264794382 0 401.47101017024056 
0.019179102616724886 0 366.1138808332992 
0.01519911082952934 0 333.7303724176411 
0.012045035402587823 0 304.12344512646683 
0.009545484566618337 0 277.0908078179923 
0.007564633275546291 0 252.43142579182566 
0.005994842503189409 0 229.9506845168239 
0.0047508101621027985 0 209.4639216334459 
0.0037649358067924675 0 190.79846453230732 
0.0029836472402833404 0 173.7944979965304 
0.002364489412645407 0 158.30511336966694 
0.001873817422860385 0 144.19584238751838 
0.001484968262254465 0 131.3439078522798 
0.0011768119524349992 0 119.63735291927999 
0.0009326033468832199 0 108.97415009692476 
0.0007390722033525783 0 99.26134462759504 
0.0005857020818056667 0 90.4142560897078 
0.00046415888336127773 0 82.3557447693315 
0.0003678379771828634 0 75.01554137906122 
0.0002915053062825176 0 68.32963584964936 
0.00023101297000831605 0 62.23972031010103 
0.0001830738280295368 0 56.69268153454809 
0.000145082877849594 0 51.64013849044402 
0.00011497569953977356 0 47.03802099578455 
9.111627561154887e-05 0 42.84618584263836 
7.220809018385471e-05 1 41.54924769181515 [DSFLSH error 1] One or more inputs are out of range; Temperature below triple-point or minimum temperature: T = 41.5492 K, Tmin = 59.7500 K.
```

**Comment by slindorfer** [comment]
Ok great, this is exactly what I need then. Sadly enabling SATSPLN did not fix it. I will move forward with upgrading to v10. Thank you!

**Comment by EricLemmon** [comment]
Look at this issue for some information that might help:

https://github.com/usnistgov/REFPROP-issues/issues/324
