### ISSUE TITLE
PSFLSH error 247 (refprop.dll v9.1) 

### ISSUE THREAD

**Issue by wenminluo** [usnistgov/REFPROP-issues#74]
I ran a series of PSFLSH iterative calcs on R1233ZD and hmx.bnc. There will always be an error and the program will terminate.The detail of the error is "	[PSFLSH error 247] density iteration for single-phase state did not converge:  [TPRHO error 202] liquid iteration has not converged for T =  434.77 K, P = 0.10845 MPa, rho (last guess) =   5.8905 mol/L, compositions =   1.00000" 
      How do you understand and if anyone has encountered the same problem?

Note: the log of the params of the PSFLSH function is
pressurekPA11:108.453329	
00004865	3.68664265	[5952] s:228.510315	
00004866	3.68670559	[5952] xMole Begin	
00004867	3.68679762	[5952] 1.000000	
00004868	3.68688774	[5952] 0.000000	
00004869	3.68697762	[5952] 0.000000	
00004870	3.68706775	[5952] 0.000000	
00004871	3.68715739	[5952] 0.000000	
00004872	3.68724775	[5952] 0.000000	
00004873	3.68734026	[5952] 0.000000	
00004874	3.68742943	[5952] 0.000000	
00004875	3.68752003	[5952] 0.000000	
00004876	3.68760991	[5952] 0.000000	
00004877	3.68769908	[5952] 0.000000	
00004878	3.68778801	[5952] 0.000000	
00004879	3.68787742	[5952] 0.000000	
00004880	3.68796659	[5952] 0.000000	
00004881	3.68805623	[5952] 0.000000	
00004882	3.68814588	[5952] 0.000000	
00004883	3.68823504	[5952] 0.000000	
00004884	3.68832850	[5952] 0.000000	
00004885	3.68843651	[5952] 0.000000	
00004886	3.68854260	[5952] 0.000000	
00004887	3.68861985	[5952] xMole End	
00004888	3.68873429	[5952] temperaure:434.766499	
00004889	3.68884730	[5952] densityMole:5.890488	
00004890	3.68895602	[5952] densityLiquidMole:0.000000	
00004891	3.68912339	[5952] densityVaporMole:0.000000	
00004892	3.68920231	[5952] xLiquid Begin---	
00004893	3.68933153	[5952] 1.000000	
00004894	3.68943858	[5952] 0.000000	
00004895	3.68954539	[5952] 0.000000	
00004896	3.68965125	[5952] 0.000000	
00004897	3.68975735	[5952] 0.000000	
00004898	3.68986320	[5952] 0.000000	
00004899	3.68996954	[5952] 0.000000	
00004900	3.69007564	[5952] 0.000000	
00004901	3.69018197	[5952] 0.000000	
00004902	3.69028902	[5952] 0.000000	
00004903	3.69039536	[5952] 0.000000	
00004904	3.69050455	[5952] 0.000000	
00004905	3.69059157	[5952] 0.000000	
00004906	3.69068122	[5952] 0.000000	
00004907	3.69077039	[5952] 0.000000	
00004908	3.69085956	[5952] 0.000000	
00004909	3.69094825	[5952] 0.000000	
00004910	3.69103742	[5952] 0.000000	
00004911	3.69112611	[5952] 0.000000	
00004912	3.69121480	[5952] 0.000000	
00004913	3.69130182	[5952] xLiquid End---	
00004914	3.69141364	[5952] xVapor Begin---	
00004915	3.69178653	[5952] 1.000000	
00004916	3.69180965	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004917	3.69204211	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004918	3.69228888	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004919	3.69249797	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004920	3.69272447	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004921	3.69295096	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004922	3.69317746	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004923	3.69340205	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004924	3.69362473	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004925	3.69384694	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004926	3.69406915	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004927	3.69427991	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004928	3.69450188	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004929	3.69472384	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004930	3.69494700	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004931	3.69517350	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004932	3.69560528	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004933	3.69583178	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004934	3.69605398	[5952] -6277438562204192200000000000000000000000000000000000000000000000000.000000	
00004935	3.69613504	[5952] xVapor End---	
00004936	3.69626617	[5952] quantity:999.000000	
00004937	3.69638228	[5952] e:0.000000	
00004938	3.69652724	[5952] h:0.000000	
00004939	3.69708824	[5952] Cv:-276466212667488380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.000000	
00004940	3.69763732	[5952] Cp:424639936394723490000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.000000	
00004941	3.69775987	[5952] w:0.000000	
00004942	3.69837642	[5952] iError:247	
00004943	3.69847059	[5952] strError:	
00004944	3.69855809	[5952] [PSFLSH error 247] density iteration for single-phase state did not converge:  [TPRHO error 202] liquid iteration has not converged for T =  434.77 K, P = 0.10845 MPa, rho (last guess) =   5.8905 mol/L, compositions =   1.00000

**Comment by ianhbell** [comment]
Can you please post the code used to generate these outputs?

**Comment by wenminluo** [comment]
Tank you for your reply. I am sorry, the code belong to my company and is protected intellectual property. But, currently, I can provide the detail log to you. The hyperlink of the log is on the github that I was replying to you.




在 2018-11-27 23:08:52，"Ian Bell" <notifications@github.com> 写道：
Can you please post the code used to generate these outputs?

**Comment by wenminluo** [comment]
> Can you please post the code used to generate these outputs?

The detail is in https://github.com/wenminluo/PSFLSH_Error_247. The version of my refprop.dll is 9.1

**Comment by ianhbell** [comment]
Unfortunately, I can’t debug this code without a much better idea of what inputs you are using.  Can you make a non-proprietary version of your sample code to demonstrate the problem?

Also, is this a custom HMX.BNC, or the standard one from REFPROP 9.1?

**Comment by wenminluo** [comment]
> Unfortunately, I can’t debug this code without a much better idea of what inputs you are using. Can you make a non-proprietary version of your sample code to demonstrate the problem? Also, is this a custom HMX.BNC, or the standard one from REFPROP 9.1?

Thank you,I am trying do that.And the HMX.BNC should be standard, and you 
check it on https://github.com/wenminluo/PSFLSH_Error_247 where I had upload it in.

**Comment by wenminluo** [comment]
The full call logic of the refprop.dll is on https://github.com/wenminluo/PSFLSH_Error_247/blob/master/Output-Debug .
Is anyone encountered a similar problem?

**Comment by ianhbell** [comment]
Can you please provide a simple example (without your proprietary information) that I can run in one of : Python, MATLAB, C# or Excel?  Otherwise, I can’t reverse-engineer the calls that resulted in these problems.

**Comment by wenminluo** [comment]
> Can you please provide a simple example (without your proprietary information) that I can run in one of : Python, MATLAB, C# or Excel? Otherwise, I can’t reverse-engineer the calls that resulted in these problems.
Thanks! I just need even a little thought now. This is why I sent this log.
 I am trying to privide a simple example to you, as you see through the log, it is a little bit complicated,but I think this is only a matter of time.

**Comment by wenminluo** [comment]
> Can you please provide a simple example (without your proprietary information) that I can run in one of : Python, MATLAB, C# or Excel? Otherwise, I can’t reverse-engineer the calls that resulted in these problems.

Doctor ianhbell ：
 I have uploaded the  simple example code.

**Comment by wenminluo** [comment]
> > Can you please provide a simple example (without your proprietary information) that I can run in one of : Python, MATLAB, C# or Excel? Otherwise, I can’t reverse-engineer the calls that resulted in these problems.
> 
> Doctor ianhbell ：
> I have uploaded the simple example code.

https://github.com/wenminluo/PSFLSH_Error247_TestProject/tree/master

**Comment by wenminluo** [comment]
> Can you please provide a simple example (without your proprietary information) that I can run in one of : Python, MATLAB, C# or Excel? Otherwise, I can’t reverse-engineer the calls that resulted in these problems.

The test project is on https://github.com/wenminluo/PSFLSH_Error247_TestProject/tree/master

There will be a few errors and there will be no problems, but the frequency is still very high. Please debug the error message several times under the error message of the "NISTPropertyBase::EnthalpyByPressureEntropy" function. The error can be reproduced.
Thanks! And looking forward to your reply!

**Comment by wenminluo** [comment]
> Can you please provide a simple example (without your proprietary information) that I can run in one of : Python, MATLAB, C# or Excel? Otherwise, I can’t reverse-engineer the calls that resulted in these problems.

Doctor：
   Excuse me, is there any clue？ thank you！

**Comment by ianhbell** [comment]
So far I cannot run your example - can you give me some quick instructions on how to run it?  Visual Studio 15 Express doesn’t like your project files …

**Comment by wenminluo** [comment]
> So far I cannot run your example - can you give me some quick instructions on how to run it? Visual Studio 15 Express doesn’t like your project files …
Hello, what is wrong? My running environment is Microsoft Visual Studio Enterprise 2015 + Visual C++ 2015 + Visual c# 2015

**Comment by wenminluo** [comment]
> So far I cannot run your example - can you give me some quick instructions on how to run it? Visual Studio 15 Express doesn’t like your project files …

I just found an empty directory and downloaded the code from github and ran it again. It is ok. What is wrong with your specific side? I can test it here.

**Comment by ianhbell** [comment]
I cloned your repo, opened the project in Visual Studio 15 Express (this might be the problem), tried to press F5 to run, didn't work, complained about missing dependencies.  What is the exact order of operations you used?

**Comment by VietTru** [comment]
Hi,
I have the same error occurred when running the REFPROP. Each time I change the input temperature, the output enthalpy appears error. Then it needs to manual update the links. The original file is attached for more information.
Thanks for helping.
[ask error Refprop.xlsx](https://github.com/usnistgov/REFPROP-issues/files/2740456/ask.error.Refprop.xlsx)
Best regards,
/Trung Pham

**Comment by EricLemmon** [comment]
Hi Trung,

I apologize for the slow response, the government shutdown meant that we could not work on Refprop related questions.  

Are you still having problems with this?

Eric

**Comment by VietTru** [comment]
Hi Eric, 
It seems an old bug that has been fixed with new version of RefProp. My colleague had the same issue. He gave me a new version file. I installed and it works. Hopefully, in term of licence, this is legal to do so. Otherwise, I need an official new installation file (my installation file is in a CDs 2013). I still keep invoice for the licence. How do you think?

**Comment by VietTru** [comment]
Hi Eric,
It seems an old bug that has been fixed with new version of RefProp. My colleague had the same issue. He gave me a new version file. I installed and it works. Hopefully, in term of licence, this is legal to do so. Otherwise, I need an official new installation file (my installation file is in a CDs 2013). I still keep invoice for the licence. How do you think?
Have a good day.
Best regards,
//Trung Pham

**Comment by VietTru** [comment]
Hi Eric,
Yes, it is still a problem. The installation file was from a CD 2013 (purchased in 2016). There is bug in the RefProp v.9.1. 
Is it possible to get a legal copy of V9.1 by downloading instead of installation via CD? Thanks,
//Trung Pham

**Comment by ianhbell** [comment]
Can you please email me (ian.bell@nist.gov) and I can send a link for installation?

**Comment by VietTru** [comment]
I tried the new installation and it worked. Thanks a lot.

**Comment by wenminluo** [comment]
> 
> 
> Can you please email me ([ian.bell@nist.gov](mailto:ian.bell@nist.gov)) and I can send a link for installation?

Hi ianhbell,
My problem is still exist.Can you also send a link to me for installation?Thanks!

**Comment by ianhbell** [comment]
@wenminluo Can you please email me (ian.bell@nist.gov) with your license information and I'll send you the link?

**Comment by wenminluo** [comment]
> 
> 
> @wenminluo Can you please email me ([ian.bell@nist.gov](mailto:ian.bell@nist.gov)) with your license information and I'll send you the link?

Ok,I am looking for a company to purchase proof, I will send it to you later with the company's email address, thank you!

**Comment by wenminluo** [comment]
> 
> 
> @wenminluo Can you please email me ([ian.bell@nist.gov](mailto:ian.bell@nist.gov)) with your license information and I'll send you the link?

Ok！The proof of purchase, will be sent to you later by the company's mailbox, thank you!

**Comment by wenminluo** [comment]
> 
> 
> @wenminluo Can you please email me ([ian.bell@nist.gov](mailto:ian.bell@nist.gov)) with your license information and I'll send you the link?
Hi ianhbell,
Does REFPROP V10.0 support multithreading? We plan to buy the latest version.Thanks！

**Comment by EricLemmon** [comment]
See #122 about multi-threading
